local constants = require("builtin.constants")

require("aerial").setup({
  layout = {
    width = constants.layout.sidebar.scale,
  },
  update_events = "TextChanged,InsertLeave,WinEnter,BufEnter,BufNewFile,BufReadPost,BufWinEnter,BufWinLeave,TabEnter,BufWritePost,CmdlineLeave,CmdwinLeave,TermLeave,TermClose,DirChanged,DiffUpdated,FocusGained,FocusLost",
  show_guides = true,
  filter_kind = {
    -- "Array",
    -- "Boolean",
    "Class",
    -- "Constant",
    "Constructor",
    "Enum",
    "EnumMember",
    "Event",
    -- "Field",
    "File",
    "Function",
    "Interface",
    "Key",
    "Method",
    "Module",
    "Namespace",
    -- "Null",
    -- "Number",
    "Object",
    "Operator",
    -- "Package",
    -- "Property",
    -- "String",
    "Struct",
    "TypeParameter",
    -- "Variable",
  },
})
