-- ---- Users Plugins ----

-- Please uncomment belows and rename this file to 'users.lua' to enable it.

-- local lua_keys = require("builtin.utils.plugins").lua_keys
-- local lua_init = require("builtin.utils.plugins").lua_init
-- local lua_config = require("builtin.utils.plugins").lua_config
-- local vim_init = require("builtin.utils.plugins").vim_init
-- local vim_config = require("builtin.utils.plugins").vim_config
--
-- local VeryLazy = "VeryLazy"
-- local BufRead = "BufRead"
-- local BufNewFile = "BufNewFile"
-- local CmdlineEnter = "CmdlineEnter"
-- local VimEnter = "VimEnter"
-- local InsertEnter = "InsertEnter"
--
-- return {
--     -- Copilot
--     {
--         "zbirenbaum/copilot-cmp",
--         event = { VeryLazy, InsertEnter, CmdlineEnter },
--         config = lua_config("zbirenbaum/copilot-cmp"),
--     },
--     {
--         "zbirenbaum/copilot.lua",
--         event = { VeryLazy, InsertEnter, CmdlineEnter },
--         config = lua_config("zbirenbaum/copilot.lua"),
--     },
--     -- Tags collector
--     {
--         "ludovicchabant/vim-gutentags",
--         event = { VeryLazy, BufRead, BufNewFile },
--         init = vim_init("ludovicchabant/vim-gutentags"),
--     },
--     -- Tags source for nvim-cmp
--     {
--         "quangnguyen30192/cmp-nvim-tags",
--         event = { VeryLazy, InsertEnter, CmdlineEnter },
--     },
--     -- Yank Improve
--     {
--         "gbprod/yanky.nvim",
--         config = lua_config("gbprod/yanky.nvim"),
--         keys = lua_keys("gbprod/yanky.nvim"),
--     },
-- }

return {}