-- ---- Users Plugins ----

-- Please uncomment belows and rename this file to 'users.lua' to enable it.

-- local lua_keys = require("builtin.utils.plugin").lua_keys
-- local lua_init = require("builtin.utils.plugin").lua_init
-- local lua_config = require("builtin.utils.plugin").lua_config
-- local vim_init = require("builtin.utils.plugin").vim_init
-- local vim_config = require("builtin.utils.plugin").vim_config
--
-- local VeryLazy = "VeryLazy"
-- local BufRead = "BufRead"
-- local BufNewFile = "BufNewFile"
-- local CmdlineEnter = "CmdlineEnter"
-- local VimEnter = "VimEnter"
-- local InsertEnter = "InsertEnter"
--
-- return {
--     -- Copilot
--     {
--         "zbirenbaum/copilot-cmp",
--         event = { VeryLazy, InsertEnter, CmdlineEnter },
--         config = lua_config("zbirenbaum/copilot-cmp"),
--     },
--     {
--         "zbirenbaum/copilot.lua",
--         event = { VeryLazy, InsertEnter, CmdlineEnter },
--         config = lua_config("zbirenbaum/copilot.lua"),
--     },
--     -- Tags collector
--     {
--         "ludovicchabant/vim-gutentags",
--         event = { VeryLazy, BufRead, BufNewFile },
--         init = vim_init("ludovicchabant/vim-gutentags"),
--     },
--     -- Tags source for nvim-cmp
--     {
--         "quangnguyen30192/cmp-nvim-tags",
--         event = { VeryLazy, InsertEnter, CmdlineEnter },
--     },
--     -- Yank Improve
--     {
--         "gbprod/yanky.nvim",
--         config = lua_config("gbprod/yanky.nvim"),
--         keys = lua_keys("gbprod/yanky.nvim"),
--     },
--     -- UI improved
--     {
--         "folke/noice.nvim",
--         event = { VimEnter },
--         dependencies = {
--             "MunifTanjim/nui.nvim",
--             "rcarriga/nvim-notify",
--         },
--         config = lua_config("folke/noice.nvim"),
--     },
--     {
--         "rcarriga/nvim-notify",
--         config = lua_config("rcarriga/nvim-notify"),
--         lazy = true,
--     },
--     -- Lazygit
--     {
--         "kdheepak/lazygit.nvim",
--         dependencies = { "akinsho/toggleterm.nvim" },
--         init = lua_init("kdheepak/lazygit.nvim"),
--         keys = lua_keys("kdheepak/lazygit.nvim"),
--     },
--     -- Lf file manager
--     {
--         "lmburns/lf.nvim",
--         config = lua_config("lmburns/lf.nvim"),
--         keys = lua_keys("lmburns/lf.nvim"),
--     },
-- }

return {}